Enable x86 and arm64

diff --git a/tcpdump_build_armeabi b/tcpdump_build_armeabi
--- a/tcpdump_build_armeabi
+++ b/tcpdump_build_armeabi
@@ -2,10 +2,10 @@
 
 # --------------------------------------
 #
-#     Title: build-tcpdump
-#    Author: EAK TEAM ELECTRONICS, EMAIL : info@eakteam.com
+#    Title: build-tcpdump
+#    Author: Dio.Ye, EMAIL : diov87@outlook.com
 #
-#   Purpose: download & build tcpdump for arm android platform
+#    Purpose: download & build tcpdump for arm android platform
 #
 # You have to define your android NDK directory before calling this script
 # example:
@@ -17,34 +17,33 @@ tcpdump_ver=4.9.2
 libpcap_ver=1.9.0
 android_api_def=21
 toolchain_abi=arm
-ndk_dir_def=ndk-r19c #change your ndk path here
-bin_dir=armeabi
+ndk_dir_def=ndk-r20
+bin_dir=armeabi-v7a
 
 #-------------------------------------------------------#
 
 tcpdump_dir=tcpdump-${tcpdump_ver}
 libpcap_dir=libpcap-${libpcap_ver}
 
-
-if [[ ${NDK} ]]
+if [[ ${ANDROID_NDK_HOME} ]]
 then
-	ndk_dir=${NDK}
+    ndk_dir=${ANDROID_NDK_HOME}
 else
-	ndk_dir=${ndk_dir_def}
+    ndk_dir=${ndk_dir_def}
 fi
 
 if [[ "$(uname -s)" = 'Linux' ]]
 then
-	ndk_dir=$(readlink -f ${ndk_dir})
+    ndk_dir=$(readlink -f ${ndk_dir})
 else
-	ndk_dir=$(perl -e 'use Cwd "abs_path";print abs_path(shift)' "${ndk_dir}")
+    ndk_dir=$(perl -e 'use Cwd "abs_path";print abs_path(shift)' "${ndk_dir}")
 fi
 
 if [[ ${ANDROID_API} ]]
 then
-	android_api=${ANDROID_API}
+    android_api=${ANDROID_API}
 else
-	android_api=${android_api_def}
+    android_api=${android_api_def}
 fi
 
 echo "_______________________"
@@ -55,228 +54,228 @@ echo "_______________________"
 
 exit_error()
 {
-	echo " _______"
-	echo "|       |"
-	echo "| ERROR |"
-	echo "|_______|"
-	exit 1
+    echo " _______"
+    echo "|       |"
+    echo "| ERROR |"
+    echo "|_______|"
+    exit 1
 }
 
 {
-	if [[ $# -ne 0 ]]
-	then
-		if [[ -d $1 ]]
-		then
-			cd "$1" || return
-		else
-			echo directory "$1" not found
-			exit_error
-		fi
-	else
-		mkdir tcpdumpbuild
-		cd tcpdumpbuild || return
-	fi
+    if [[ $# -ne 0 ]]
+    then
+        if [[ -d $1 ]]
+        then
+            cd "$1" || return
+        else
+            echo directory "$1" not found
+            exit_error
+        fi
+    else
+        mkdir tcpdumpbuild
+        cd tcpdumpbuild || return
+    fi
 }
-
 
 # Prepare toolchains
 {
-	echo " ____________________"
-	echo "|                    |"
-	echo "| TOOLCHAIN          |"
-	echo "|____________________|"
-	
-	toolchain=toolchain/${toolchain_abi}
-	if [[ -d toolchain ]]
-	then
-		echo Toolchain already exist! Nothing to do.
-	else
-		echo Creating toolchain...
-		mkdir -p ${toolchain}
-		
-		if ! "${ndk_dir}"/build/tools/make_standalone_toolchain.py --arch=${toolchain_abi} --api=${android_api} --install-dir=${toolchain}  --force
-		then
-			rm -fr ${toolchain}
-			exit_error
-		fi
-	fi
+    toolchain=toolchain/${toolchain_abi}
+    if [[ -d toolchain ]]
+    then
+        echo Toolchain already exist! Nothing to do.
+    else
+        echo Creating toolchain...
+        mkdir -p ${toolchain}
 
-	PATH=$(pwd)/${toolchain}/bin:$PATH
+        if ! "${ndk_dir}"/build/tools/make_standalone_toolchain.py --arch=${toolchain_abi} --api=${android_api} --install-dir=${toolchain}  --force
+        then
+            rm -fr "${toolchain}"
+            exit_error
+        fi
+    fi
+
+    # toolchain=${ndk_dir}/toolchains/llvm/prebuilt/darwin-x86_64
+    # PATH=${toolchain}/bin:$PATH
+    PATH=$(pwd)/${toolchain}/bin:$PATH
     export PATH
 
-	target_host=arm-linux-androideabi
+    target_host=arm-linux-androideabi
     export AR=${target_host}-ar
     export AS=${target_host}-clang
     export CC=${target_host}-clang
     export CXX=${target_host}-clang++
     export LD=${target_host}-ld
     export STRIP=${target_host}-strip
-	export RANLIB=${target_host}-ranlib
-	export STRIP=${target_host}-strip
-	export CFLAGS="-static -O2 -fPIE -fPIC -march=armv7-a -mthumb -mfloat-abi=softfp -mfpu=vfpv3-d16 -mfpu=neon -march=armv7-a -Wl,--fix-cortex-a8"
+    export RANLIB=${target_host}-ranlib
+    export STRIP=${target_host}-strip
+    export CFLAGS="-static -O2 -fPIE -fPIC -march=armv7-a -mthumb -mfloat-abi=softfp -mfpu=vfpv3-d16 -mfpu=neon -march=armv7-a -Wl,--fix-cortex-a8"
     export LDFLAGS="-pie"
+
+    echo PATH $PATH
+    echo $CC
 }
 
 # download & untar libpcap + tcpdump
 {
-	echo " _______________________________"
-	echo "|                               |"
-	echo "| DOWNLOADING LIBPCAP & TCPDUMP |"
-	echo "|_______________________________|"
-	
-	asc_file=signing-key.asc
-	tcpdump_file=${tcpdump_dir}.tar.gz
-	libpcap_file=${libpcap_dir}.tar.gz
-	public_asc=http://www.tcpdump.org/release/${asc_file}
-	tcpdump_link=http://www.tcpdump.org/release/${tcpdump_file}
-	libpcap_link=http://www.tcpdump.org/release/${libpcap_file}
-	
-	if [[ -f ${asc_file} ]]
-	then
-		echo ${asc_file} already downloaded! Nothing to do.
-	else
-		echo Download ${asc_file}...
-		wget ${public_asc}
-		if [[ ! -f ${asc_file} ]]
-		then
-			exit_error
-		fi
-	fi
+    echo " _______________________________"
+    echo "|                               |"
+    echo "| DOWNLOADING LIBPCAP & TCPDUMP |"
+    echo "|_______________________________|"
 
-	if ! gpg --import ${asc_file}
-	then
-		exit_error
-	fi
+    asc_file=signing-key.asc
+    tcpdump_file=${tcpdump_dir}.tar.gz
+    libpcap_file=${libpcap_dir}.tar.gz
+    public_asc=http://www.tcpdump.org/release/${asc_file}
+    tcpdump_link=http://www.tcpdump.org/release/${tcpdump_file}
+    libpcap_link=http://www.tcpdump.org/release/${libpcap_file}
 
-	if [[ -f ${tcpdump_file} ]]
-	then
-		echo ${tcpdump_file} already downloaded! Nothing to do.
-	else
-		echo Download ${tcpdump_file}...
-		wget ${tcpdump_link}
-		wget ${tcpdump_link}.sig
-		if [[ ! -f ${tcpdump_file} ]]
-		then
-			exit_error
-		fi
-	fi
+    if [[ -f ${asc_file} ]]
+    then
+        echo ${asc_file} already downloaded! Nothing to do.
+    else
+        echo Download ${asc_file}...
+        wget ${public_asc}
+        if [[ ! -f ${asc_file} ]]
+        then
+            exit_error
+        fi
+    fi
 
-	if ! gpg --verify ${tcpdump_file}.sig
-	then
-		exit_error
-	fi
+    if ! gpg --import ${asc_file}
+    then
+        exit_error
+    fi
 
-	
-	if [[ -f ${libpcap_file} ]]
-	then
-		echo ${libpcap_file} already downloaded! Nothing to do.
-	else
-		echo Download ${libpcap_file}...
-		wget ${libpcap_link}
-		wget ${libpcap_link}.sig
-		if [[ ! -f ${libpcap_file} ]]
-		then
-			exit_error
-		fi
-	fi
+    if [[ -f ${tcpdump_file} ]]
+    then
+        echo ${tcpdump_file} already downloaded! Nothing to do.
+    else
+        echo Download ${tcpdump_file}...
+        wget ${tcpdump_link}
+        wget ${tcpdump_link}.sig
+        if [[ ! -f ${tcpdump_file} ]]
+        then
+            exit_error
+        fi
+    fi
 
-	if ! gpg --verify ${libpcap_file}.sig
-	then
-		exit_error
-	fi
+    if ! gpg --verify ${tcpdump_file}.sig
+    then
+        exit_error
+    fi
 
-	
-	if [[ -d ${tcpdump_dir} ]]
-	then
-		make clean -C ${tcpdump_dir}
-		echo ${tcpdump_dir} directory already exist! Clean previous configure.
-	else
-		echo untar ${tcpdump_file}
-		tar -zxf ${tcpdump_file}
-	fi
-	
-	if [[ -d ${libpcap_dir} ]]
-	then
-		make clean -C ${libpcap_dir}
-		echo ${libpcap_dir} directory already exist! Clean previous configure.
-	else
-		echo untar ${libpcap_file}
-		tar -zxf ${libpcap_file}
-	fi
+
+    if [[ -f ${libpcap_file} ]]
+    then
+        echo ${libpcap_file} already downloaded! Nothing to do.
+    else
+        echo Download ${libpcap_file}...
+        wget ${libpcap_link}
+        wget ${libpcap_link}.sig
+        if [[ ! -f ${libpcap_file} ]]
+        then
+            exit_error
+        fi
+    fi
+
+    if ! gpg --verify ${libpcap_file}.sig
+    then
+        exit_error
+    fi
+
+
+    if [[ -d ${tcpdump_dir} ]]
+    then
+        make clean -C ${tcpdump_dir}
+        echo ${tcpdump_dir} directory already exist! Clean previous configure.
+    else
+        echo untar ${tcpdump_file}
+        tar -zxf ${tcpdump_file}
+    fi
+
+    if [[ -d ${libpcap_dir} ]]
+    then
+        make clean -C ${libpcap_dir}
+        echo ${libpcap_dir} directory already exist! Clean previous configure.
+    else
+        echo untar ${libpcap_file}
+        tar -zxf ${libpcap_file}
+    fi
 }
 
 # build libpcap
 {
-	cd "${libpcap_dir}" || return
+    cd "${libpcap_dir}" || return
 
-	echo " _____________________"
-	echo "|                     |"
-	echo "| CONFIGURING LIBPCAP |"
-	echo "|_____________________|"
+    echo " _____________________"
+    echo "|                     |"
+    echo "| CONFIGURING LIBPCAP |"
+    echo "|_____________________|"
 
-	chmod +x configure
+    chmod +x configure
 
-	if ! ./configure --host=armv7a-linux-androideabi --with-pcap=linux
-	then
-		exit_error
-	fi	
+    if ! ./configure --host=armv7a-linux-androideabi --with-pcap=linux
+    then
+        exit_error
+    fi
 
-	echo " __________________"
-	echo "|                  |"
-	echo "| BUILDING LIBPCAP |"
-	echo "|__________________|"
+    echo " __________________"
+    echo "|                  |"
+    echo "| BUILDING LIBPCAP |"
+    echo "|__________________|"
 
-	chmod +x runlex.sh
-	
-	if ! make
-	then
-		exit_error
-	fi
+    chmod +x runlex.sh
+
+    if ! make
+    then
+        exit_error
+    fi
 
     cd ..
 }
 
 # build tcpdump
 {
-	cd ${tcpdump_dir} || return
-	
-	echo " _____________________"
-	echo "|                     |"
-	echo "| CONFIGURING TCPDUMP |"
-	echo "|_____________________|"
-	
-	chmod +x configure
+    cd ${tcpdump_dir} || return
 
-	if ! ./configure --host=arm-linux-androideabi --with-pcap=linux
-	then
-		exit_error
-	fi	
+    echo " _____________________"
+    echo "|                     |"
+    echo "| CONFIGURING TCPDUMP |"
+    echo "|_____________________|"
 
-	echo " __________________"
-	echo "|                  |"
-	echo "| BUILDING TCPDUMP |"
-	echo "|__________________|"
-	
-	#setprotoent endprotoen not supported on android
-	sed -i".bak" "s/setprotoent/\/\/setprotoent/g" print-isakmp.c
-	sed -i".bak" "s/endprotoent/\/\/endprotoent/g" print-isakmp.c
+    chmod +x configure
 
-	#NBBY is not defined => FORCE definition
-	
-	if ! make #CFLAGS=-DNBBY=8 # for tcpdump < 4.2.1 (CFLAGS refefined in Makefile) => just make
-	then
-		exit_error
-	fi
-	
-	cd ..
+    if ! ./configure --host=arm-linux-androideabi --with-pcap=linux
+    then
+        exit_error
+    fi
+
+    echo " __________________"
+    echo "|                  |"
+    echo "| BUILDING TCPDUMP |"
+    echo "|__________________|"
+
+    #setprotoent endprotoen not supported on android
+    sed -i".bak" "s/setprotoent/\/\/setprotoent/g" print-isakmp.c
+    sed -i".bak" "s/endprotoent/\/\/endprotoent/g" print-isakmp.c
+
+    #NBBY is not defined => FORCE definition
+
+    if ! make #CFLAGS=-DNBBY=8 # for tcpdump < 4.2.1 (CFLAGS refefined in Makefile) => just make
+    then
+        exit_error
+    fi
+
+    cd ..
 }
 
-mkdir -p ${bin_dir}
-cp ${tcpdump_dir}/tcpdump ./${bin_dir}
-chmod +x ./${bin_dir}/tcpdump
+output_dir=../output/${bin_dir}
+mkdir -p ${output_dir}
+cp ${tcpdump_dir}/tcpdump ${output_dir}
+chmod +x ${output_dir}/tcpdump
 
 echo " __________________"
 echo "|                  |"
 echo "| TCPDUMP IS READY |"
 echo "|__________________|"
-echo "$(pwd)"/${bin_dir}/tcpdump
+echo ${output_dir}/tcpdump
diff --git a/tcpdump_build_x86 b/tcpdump_build_x86
--- a/tcpdump_build_x86
+++ b/tcpdump_build_x86
@@ -2,10 +2,10 @@
 
 # --------------------------------------
 #
-#     Title: build-tcpdump
-#    Author: EAK TEAM ELECTRONICS, EMAIL : info@eakteam.com
+#    Title: build-tcpdump
+#    Author: Dio.Ye, EMAIL : diov87@outlook.com
 #
-#   Purpose: download & build tcpdump for x86 android platform
+#    Purpose: download & build tcpdump for x86 android platform
 #
 # You have to define your android NDK directory before calling this script
 # example:
@@ -13,37 +13,40 @@
 #
 # --------------------------------------
 
-# default, edit versions
 tcpdump_ver=4.9.2
-libpcap_ver=1.8.1
-android_api_def=16
-toolchain=x86-4.9
-ndk_dir_def=ndk-r17b
+libpcap_ver=1.9.0
+android_api_def=21
+toolchain_abi=x86
+ndk_dir_def=ndk-r20
+bin_dir=x86
 
 #-------------------------------------------------------#
 
 tcpdump_dir=tcpdump-${tcpdump_ver}
 libpcap_dir=libpcap-${libpcap_ver}
 
-
-if [ ${NDK} ]
+if [[ ${ANDROID_NDK_HOME} ]]
 then
-	ndk_dir=${NDK}
+    ndk_dir=${ANDROID_NDK_HOME}
 else
-	ndk_dir=${ndk_dir_def}
+    ndk_dir=${ndk_dir_def}
 fi
 
-ndk_dir=`readlink -f ${ndk_dir}`
-
-if [ ${ANDROID_API} ]
+if [[ "$(uname -s)" = 'Linux' ]]
 then
-	android_api=${ANDROID_API}
+    ndk_dir=$(readlink -f ${ndk_dir})
 else
-	android_api=${android_api_def}
+    ndk_dir=$(perl -e 'use Cwd "abs_path";print abs_path(shift)' "${ndk_dir}")
+fi
+
+if [[ ${ANDROID_API} ]]
+then
+    android_api=${ANDROID_API}
+else
+    android_api=${android_api_def}
 fi
 
 echo "_______________________"
-echo ""
 echo "NDK - ${ndk_dir}"
 echo "Android API: ${android_api}"
 echo "_______________________"
@@ -51,209 +54,223 @@ echo "_______________________"
 
 exit_error()
 {
-	echo " _______"
-	echo "|       |"
-	echo "| ERROR |"
-	echo "|_______|"
-	exit 1
+    echo " _______"
+    echo "|       |"
+    echo "| ERROR |"
+    echo "|_______|"
+    exit 1
 }
 
 {
-	if [ $# -ne 0 ]
-	then
-		if [ -d $1 ]
-		then
-			cd $1
-		else
-			echo directory $1 not found
-			exit_error
-		fi
-	else
-		mkdir tcpdumpbuild
-		cd tcpdumpbuild
-	fi
+    if [[ $# -ne 0 ]]
+    then
+        if [[ -d $1 ]]
+        then
+            cd "$1" || return
+        else
+            echo directory "$1" not found
+            exit_error
+        fi
+    else
+        mkdir tcpdumpbuild
+        cd tcpdumpbuild || return
+    fi
 }
 
-
-
+# Prepare toolchains
 {
-	echo " ____________________"
-	echo "|                    |"
-	echo "| TOOLCHAIN          |"
-	echo "|____________________|"
+    toolchain=toolchain/${toolchain_abi}
+    if [[ -d toolchain ]]
+    then
+        echo Toolchain already exist! Nothing to do.
+    else
+        echo Creating toolchain...
+        mkdir -p ${toolchain}
 
-	if [ -d toolchain ]
-	then
-		echo Toolchain already exist! Nothing to do.
-	else
-		echo Creating toolchain...
-		mkdir toolchain
-		bash ${ndk_dir}/build/tools/make-standalone-toolchain.sh --force --toolchain=${toolchain} --platform=android-${android_api} --install-dir=toolchain
-		
-		if [ $? -ne 0 ]
-		then
-			rm -fr toolchain
-			exit_error
-		fi
-	fi
-	
-	export PATH=`pwd`/toolchain/bin:$PATH
+        if ! "${ndk_dir}"/build/tools/make_standalone_toolchain.py --arch=${toolchain_abi} --api=${android_api} --install-dir=${toolchain}  --force
+        then
+            rm -fr "${toolchain}"
+            exit_error
+        fi
+    fi
 
-	target_host=i686-linux-android
+    PATH=$(pwd)/${toolchain}/bin:$PATH
+    export PATH
+
+    target_host=i686-linux-android
     export AR=$target_host-ar
     export AS=$target_host-clang
     export CC=$target_host-clang
     export CXX=$target_host-clang++
     export LD=$target_host-ld
     export STRIP=$target_host-strip
-	export RANLIB=$target_host-ranlib
-	export STRIP=$target_host-strip
-	export CFLAGS="-static -O2 -fPIE -fPIC -mthumb -mfloat-abi=softfp -Wl,--fix-cortex-a8"
+    export RANLIB=$target_host-ranlib
+    export STRIP=$target_host-strip
+    export CFLAGS="-static -O2 -fPIE -fPIC -mthumb -mfloat-abi=softfp -Wl,--fix-cortex-a8"
     export LDFLAGS="-pie"
 }
 
 # download & untar libpcap + tcpdump
 {
-	echo " _______________________________"
-	echo "|                               |"
-	echo "| DOWNLOADING LIBPCAP & TCPDUMP |"
-	echo "|_______________________________|"
-	
-	tcpdump_file=${tcpdump_dir}.tar.gz
-	libpcap_file=${libpcap_dir}.tar.gz
-	tcpdump_link=http://www.tcpdump.org/release/${tcpdump_file}
-	libpcap_link=http://www.tcpdump.org/release/${libpcap_file}
-	
-	if [ -f ${tcpdump_file} ]
-	then
-		echo ${tcpdump_file} already downloaded! Nothing to do.
-	else
-		echo Download ${tcpdump_file}...
-		wget ${tcpdump_link}
-		wget ${tcpdump_link}.sig
-		if [ ! -f ${tcpdump_file} ]
-		then
-			exit_error
-		fi
-	fi
+    echo " _______________________________"
+    echo "|                               |"
+    echo "| DOWNLOADING LIBPCAP & TCPDUMP |"
+    echo "|_______________________________|"
 
-	gpg --verify ${tcpdump_file}.sig
-	if [ $? -ne 0 ]
-	then
-		exit_error
-	fi
+    asc_file=signing-key.asc
+    tcpdump_file=${tcpdump_dir}.tar.gz
+    libpcap_file=${libpcap_dir}.tar.gz
+    public_asc=http://www.tcpdump.org/release/${asc_file}
+    tcpdump_link=http://www.tcpdump.org/release/${tcpdump_file}
+    libpcap_link=http://www.tcpdump.org/release/${libpcap_file}
 
-	
-	if [ -f ${libpcap_file} ]
-	then
-		echo ${libpcap_file} already downloaded! Nothing to do.
-	else
-		echo Download ${libpcap_file}...
-		wget ${libpcap_link}
-		wget ${libpcap_link}.sig
-		if [ ! -f ${libpcap_file} ]
-		then
-			exit_error
-		fi
-	fi
+    if [[ -f ${asc_file} ]]
+    then
+        echo ${asc_file} already downloaded! Nothing to do.
+    else
+        echo Download ${asc_file}...
+        wget ${public_asc}
+        if [[ ! -f ${asc_file} ]]
+        then
+            exit_error
+        fi
+    fi
 
-	gpg --verify ${libpcap_file}.sig
-	if [ $? -ne 0 ]
-	then
-		exit_error
-	fi
+    if ! gpg --import ${asc_file}
+    then
+        exit_error
+    fi
 
-	
-	if [ -d ${tcpdump_dir} ]
-	then
-		echo ${tcpdump_dir} directory already exist! Nothing to do.
-	else
-		echo untar ${tcpdump_file}
-		tar -zxf ${tcpdump_file}
-	fi
-	
-	if [ -d ${libpcap_dir} ]
-	then
-		echo ${libpcap_dir} directory already exist! Nothing to do.
-	else
-		echo untar ${libpcap_file}
-		tar -zxf ${libpcap_file}
-	fi
+    if [[ -f ${tcpdump_file} ]]
+    then
+        echo ${tcpdump_file} already downloaded! Nothing to do.
+    else
+        echo Download ${tcpdump_file}...
+        wget ${tcpdump_link}
+        wget ${tcpdump_link}.sig
+        if [[ ! -f ${tcpdump_file} ]]
+        then
+            exit_error
+        fi
+    fi
+
+    if ! gpg --verify ${tcpdump_file}.sig
+    then
+        exit_error
+    fi
+
+
+    if [[ -f ${libpcap_file} ]]
+    then
+        echo ${libpcap_file} already downloaded! Nothing to do.
+    else
+        echo Download ${libpcap_file}...
+        wget ${libpcap_link}
+        wget ${libpcap_link}.sig
+        if [[ ! -f ${libpcap_file} ]]
+        then
+            exit_error
+        fi
+    fi
+
+    if ! gpg --verify ${libpcap_file}.sig
+    then
+        exit_error
+    fi
+
+
+    if [[ -d ${tcpdump_dir} ]]
+    then
+        make clean -C ${tcpdump_dir}
+        echo ${tcpdump_dir} directory already exist! Clean previous configure.
+    else
+        echo untar ${tcpdump_file}
+        tar -zxf ${tcpdump_file}
+    fi
+
+    if [[ -d ${libpcap_dir} ]]
+    then
+        make clean -C ${libpcap_dir}
+        echo ${libpcap_dir} directory already exist! Clean previous configure.
+    else
+        echo untar ${libpcap_file}
+        tar -zxf ${libpcap_file}
+    fi
 }
 
 # build libpcap
 {
-	cd ${libpcap_dir}
+    cd "${libpcap_dir}" || return
 
-	echo " _____________________"
-	echo "|                     |"
-	echo "| CONFIGURING LIBPCAP |"
-	echo "|_____________________|"
-	
-	chmod +x configure
-	./configure --host=i686-linux-android --with-pcap=linux
+    echo " _____________________"
+    echo "|                     |"
+    echo "| CONFIGURING LIBPCAP |"
+    echo "|_____________________|"
 
-	if [ $? -ne 0 ]
-	then
-		exit_error
-	fi	
+    chmod +x configure
 
-	echo " __________________"
-	echo "|                  |"
-	echo "| BUILDING LIBPCAP |"
-	echo "|__________________|"
+    if ! ./configure --host=aarch64-linux-android --with-pcap=linux
+    then
+        exit_error
+    fi
 
-	chmod +x runlex.sh
-	make
+    echo " __________________"
+    echo "|                  |"
+    echo "| BUILDING LIBPCAP |"
+    echo "|__________________|"
 
-	if [ $? -ne 0 ]
-	then
-		exit_error
-	fi
+    chmod +x runlex.sh
 
-	cd ..
+    if ! make
+    then
+        exit_error
+    fi
+
+    cd ..
 }
 
 # build tcpdump
 {
-	cd ${tcpdump_dir}
-	
-	echo " _____________________"
-	echo "|                     |"
-	echo "| CONFIGURING TCPDUMP |"
-	echo "|_____________________|"
-		
-	chmod +x configure
-	./configure --host=i686-linux-android --with-pcap=linux
+    cd ${tcpdump_dir} || return
 
-	if [ $? -ne 0 ]
-	then
-		exit_error
-	fi	
+    echo " _____________________"
+    echo "|                     |"
+    echo "| CONFIGURING TCPDUMP |"
+    echo "|_____________________|"
 
-	echo " __________________"
-	echo "|                  |"
-	echo "| BUILDING TCPDUMP |"
-	echo "|__________________|"
-	
-	sed -i".bak" "s/setprotoent/\/\/setprotoent/g" print-isakmp.c
-	sed -i".bak" "s/endprotoent/\/\/endprotoent/g" print-isakmp.c
+    chmod +x configure
 
-	make
-	
-	if [ $? -ne 0 ]
-	then
-		exit_error
-	fi
-	
-	cd ..
+    if ! ./configure --host=aarch64-linux-android --with-pcap=linux
+    then
+        exit_error
+    fi
+
+    echo " __________________"
+    echo "|                  |"
+    echo "| BUILDING TCPDUMP |"
+    echo "|__________________|"
+
+    #setprotoent endprotoen not supported on android
+    sed -i".bak" "s/setprotoent/\/\/setprotoent/g" print-isakmp.c
+    sed -i".bak" "s/endprotoent/\/\/endprotoent/g" print-isakmp.c
+
+    #NBBY is not defined => FORCE definition
+
+    if ! make #CFLAGS=-DNBBY=8 # for tcpdump < 4.2.1 (CFLAGS refefined in Makefile) => just make
+    then
+        exit_error
+    fi
+
+    cd ..
 }
 
-cp ${tcpdump_dir}/tcpdump .
-chmod +x tcpdump
+output_dir=../output/${bin_dir}
+mkdir -p ${output_dir}
+cp ${tcpdump_dir}/tcpdump ${output_dir}
+chmod +x ${output_dir}/tcpdump
 
 echo " __________________"
 echo "|                  |"
 echo "| TCPDUMP IS READY |"
 echo "|__________________|"
-echo `pwd`/tcpdump
+echo ${output_dir}/tcpdump
